---
# Three Tier Application Playbook
- name: Configuring a new Three Tier Application
  hosts: apic1
  connection: local
  gather_facts: false
  
  module_defaults:
    group/cisco.aci.all:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: false

  vars_files:
    - ./host_vars/vars.yml

  tasks:
  - name: Add Bridge Domain
    cisco.aci.aci_bd:
      tenant: "{{ item.tenant_name }}"
      bd: "{{ item.bd_name }}"
      description: "{{ item.bd_description }}"
      vrf: "{{ item.vrf_name }}"
      state: present
    loop: "{{ bds_dictionary }}"

  - name: Create a subnet
    cisco.aci.aci_bd_subnet:
      tenant: "{{ item.0.tenant_name }}"
      bd: "{{ item.0.bd_name }}"
      gateway: "{{ item.1.gateway }}"
      mask: "{{ item.1.mask }}"
      state: present
    loop: "{{ bds_dictionary | subelements('ips') }}"

  - name: Add a new EPG
    cisco.aci.aci_epg:
      tenant: "{{ item.tenant_name }}"
      ap: "{{ item.application_profile_name }}"
      epg: "{{ item.epg_name }}"
      description: "{{ item.epg_description }}"
      bd: "{{ item.bd_name }}"
      state: present
    loop: "{{ epgs_dictionary }}"