---
# Three Tier Application Playbook
- name: Configuring a new Three Tier Application
  hosts: apic1
  connection: local
  gather_facts: false
  
  module_defaults:
    group/cisco.aci.all:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: false

  vars_files:
    - ./host_vars/vars.yml

  tasks:
  - name: Create Ansible Tenant
    cisco.aci.aci_tenant:
      tenant: "{{ item.tenant_name }}"
      description: "{{ item.tenant_description }}"
      state: present
    loop: "{{ tenants_dictionary }}"

  - name: Add a new VRF to a tenant
    cisco.aci.aci_vrf:
      tenant: "{{ item.tenant_name }}"
      vrf: "{{ item.vrf_name }}"
      descr: "{{ item.vrf_description }}"
      state: present
    loop: "{{ vrfs_dictionary }}"

- name: Add a new l3out to sr-mpls infra l3out
  cisco.aci.aci_l3out_to_sr_mpls_infra_l3out:
    tenant: production
    l3out: prod_l3out
    description: L3Out for Production tenant
    infra_l3out: infra_l3out_name
    external_epg: uni/tn-production/out-l3out_name/instP-external_epg_name
    outbound_route_map: uni/tn-production/prof-outbound_route_map_name
    inbound_route_map: uni/tn-production/prof-inbound_route_map_name
    state: present
  loop: "{{ vrfs_dictionary }}"