all: 
  children: 
    # apic1: 
    #   hosts: 
    #     sandboxapicdc.cisco.com:
    #       ansible_connection: ansible.netcommon.httpapi
    #       ansible_network_os: cisco.aci.aci
    #       ansible_httpapi_use_ssl: true
    #       ansible_httpapi_port: 443
    #       password: "!v3G@!4@Y"
    #       username: admin
    apic1: 
      hosts: 
        10.10.20.14:
          ansible_connection: ansible.netcommon.httpapi
          ansible_network_os: cisco.aci.aci
          ansible_httpapi_use_ssl: true
          ansible_httpapi_port: 443
          password: "C1sco12345"
          username: admin
